### ISSUE TITLE
Cannot compose sybase docker file

### ISSUE THREAD

**Issue by QuanTran91** [DataGrip/docker-env#6]
Hi all, I have created an docker compose file like this:

```
version: '3.0'
services:
  sybase:
    image: datagrip/sybase
    ports:
    - "5000:5000"

```

However, when running it, I got a message:
=============== CREATING SCHEMA ==========================
Msg 102, Level 15, State 181:
Server 'MYSYBASE', Line 1:
Incorrect syntax near 'tester'.

It seems like there is a problem with the file init3.sql. Could you please help to check?
Btw, I saw some sybase docker, adding schema is ignored (Eg: https://github.com/sercheo87/docker-images/blob/master/sybase/15.7/entrypoint.sh)
Thanks.

**Comment by tjlee** [comment]
Try the following compose configuration I use in DG test environment.

docker-compose file part:
```
 sybase157:
      # jdbc:jtds:sybase://localhost:5000/guest;user=guest;password=guest1234
      container_name: sybase157      
      image: datagrip/sybase:15.7
      ports:
        - "5000:5000"
      env_file: .env
      hostname: dksybase
      healthcheck:
        test: "exit 0"
```


.env file contents for ASE:
```
# for sybase 15.7
SYBASE_USER=guest
# password have to be more than 8 symbols
SYBASE_PASSWORD=guest1234
SYBASE_DB=guest
```
