### ISSUE TITLE
datagrip/sybase:16.0 fails to start from time to time

### ISSUE THREAD

**Issue by MaceWindu** [DataGrip/docker-env#8]
Not really sure what the reason of it - missing extra wait or isql connecting to wrong ip.

Log:
```
Status: Downloaded newer image for datagrip/sybase:16.0
3bd5ca71f0902fa49d5b463ee0dbab4c886ce55fd1d7bf16d2a822488607887f
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS                  PORTS                    NAMES
3bd5ca71f090        datagrip/sybase:16.0   "/entrypoint.sh"    6 seconds ago       Up Less than a second   0.0.0.0:5000->5000/tcp   sybase
STARTING... (about 30 sec)
=============== SYBASE STARTED ==========================
SYBASE_USER: tester
SYBASE_PASSWORD: guest1234
SYBASE_DB: TestDataCore
=============== CREATING LOGIN/PWD ==========================
CT-LIBRARY error:
	ct_connect(): network packet layer: internal net library error: Net-Lib protocol driver call to connect two endpoints failed
=============== CREATING DB ==========================
CT-LIBRARY error:
	ct_connect(): network packet layer: internal net library error: Net-Lib protocol driver call to connect two endpoints failed
=============== CREATING SCHEMA ==========================
CT-LIBRARY error:
	ct_connect(): network packet layer: internal net library error: Net-Lib protocol driver call to connect two endpoints failed
```

**Comment by MaceWindu** [comment]
Actually it could be lack of extra wait/proper start check, because tests give me this error:
```
```

**Comment by MaceWindu** [comment]
Can confirm that is it 99% issue with init scrips running to early, because it works if I run custom init script manually a bit later

**Comment by tjlee** [comment]
Could you specify the way you run your image?

I run it with docker-compose:
```
...
    sybase_16.0:
      container_name: sybase_16.0
      privileged: true
      image: datagrip/sybase:16.0
      ports:
        - "5001:5000"
      env_file: .env
      hostname: mysybase
      healthcheck:
        test: "exit 0"
...
```
Sybase related environment variables:
```
SYBASE_USER=guest
SYBASE_PASSWORD=guest1234
SYBASE_DB=guest
```

We run docker container on our CI server and have no issues with container startup.
